### ISSUE TITLE
Profiles with hundreds of dives take too long to load

### ISSUE THREAD

**Issue by pggolub** [Diveboard/android-native#23]
Currently dives are loaded all at ones and profiles with 500 dives take much time to be loaded. Introduce some kind of paging (other ideas?) and load first 50 dives at first and then load the rest in bg. API has this capability but it has to be leveraged on the mobile app.

**Comment by the0ne** [comment]
Seems to be solved with fde9d5dda3fa618294a4101441df5d0069fbb6e2 👍🏻

**Comment by pggolub** [comment]
Should be sufficient for now with two mentioned improvements
